In [5]:
import pandas as pd

import plotly.express as px

f = pd.read_pickle('../data/interim/combined.pkl')

In [6]:
f['easy_apply'] = f['easy_apply'].map(lambda x: 0 if x=='-1' else 1)

In [7]:
f.sample(20)

,job_title,job_description,rating,company_name,headquarters,size,founded,type_of_ownership,industry,sector,revenue,competitors,easy_apply,low_salary,high_salary,mid_salary,city,state
5041,Big Data Engineer,Sr. Big Data Engineer with 7+ years of program...,3.9,Horizontal Talent,"Minneapolis, MN",501 to 1000 employees,2003,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),-1,0,73000,102000,73000.0,Plano,TX
95,Data Analyst,Hagerty Consulting (www.hagertyconsulting.com)...,3.2,Hagerty Consulting,"Evanston, IL",1 to 50 employees,-1,Company - Private,Consulting,Business Services,$1 to $5 million (USD),-1,0,51000,87000,51000.0,New York,NY
4926,Big Data Engineer,Tachyon Technologies is a Digital Transformati...,4.4,Tachyon Technologies LLC,"Irving, TX",201 to 500 employees,2011,Company - Private,IT Services,Information Technology,$10 to $25 million (USD),-1,0,49000,92000,49000.0,Irving,TX
5142,Machine Learning Scientist,"About Us\n\nWe're Blue River, a team of innova...",4.5,Blue River Technology,"Sunnyvale, CA",51 to 200 employees,2011,Subsidiary or Business Segment,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,"The Climate Corp, CNH Industrial, C.A.T.",0,111000,175000,111000.0,Sunnyvale,CA
1347,Data Analyst,Financial Additions has partnered with a lead ...,4.6,Financial Additions,"Dallas, TX",1 to 50 employees,1999,Company - Private,Investment Banking & Asset Management,Finance,$5 to $10 million (USD),-1,0,30000,53000,30000.0,Dallas,TX
1085,Data Analyst - Data Science,Overview\ngoPuff is a high-growth startup that...,3.3,Gopuff,"Philadelphia, PA",1001 to 5000 employees,2013,Company - Private,Express Delivery Services,Transportation & Logistics,Unknown / Non-Applicable,-1,0,41000,78000,41000.0,Philadelphia,PA
6011,PhD. NLP Data Scientist,Job Description\nPhD. NLP Data Scientist\n\n**...,4.2,Emerald Resource Group,"Broadview Heights, OH",1 to 50 employees,1997,Company - Private,Staffing & Outsourcing,Business Services,$1 to $5 million (USD),-1,0,98000,160000,98000.0,Columbus,OH
1549,Sr. Data Warehouse Analyst,"Conceive, design and implement business techno...",3.9,AbbVie,"North Chicago, IL",10000+ employees,2013,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Amgen, Baxter, Bristol Myers Squibb",0,69000,127000,69000.0,Sunnyvale,CA
1339,Junior Data Analyst,Job Description\nJob description\nInterpret da...,5.0,"Staffigo Technical Services, LLC","Woodridge, IL",51 to 200 employees,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),-1,0,24000,48000,24000.0,Dallas,TX
5005,Full Stack Data Engineer Irving AVP/C12,The Applications Development Senior Programmer...,3.7,Citi,"New York, NY",10000+ employees,1812,Company - Public,Investment Banking & Asset Management,Finance,$10+ billion (USD),-1,0,46000,91000,46000.0,Irving,TX
4535,"Scientist, Discovery Toxicology","Who We Are:\n\n\nAt Neurocrine Biosciences, we...",4.3,Neurocrine Biosciences,"San Diego, CA",501 to 1000 employees,1992,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$500 million to $1 billion (USD),-1,0,39000,69000,39000.0,San Diego,CA
22,Data Analyst - Intex Developer,Data Analyst - Intex Developer\n\n\nNew York\n...,3.3,Macquarie Group,"Sydney, Australia",10000+ employees,1969,Company - Public,Investment Banking & Asset Management,Finance,$5 to $10 billion (USD),"Goldman Sachs, Commonwealth Bank of Australia,...",0,37000,66000,37000.0,New York,NY
3330,Staff Scientist,"Summary\nBaylor College of Medicine, Departmen...",3.6,Baylor College of Medicine,"Houston, TX",5001 to 10000 employees,1900,College / University,Colleges & Universities,Education,$1 to $2 billion (USD),-1,0,39000,87000,39000.0,Houston,TX
3636,Data Engineer role(SQL/Python/AWS)-Remote,Data Engineer role(SQL/Python/AWS) -\nContract...,4.0,Clairvoyant,"Chandler, AZ",501 to 1000 employees,2012,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,0,45000,81000,45000.0,Tempe,AZ
418,Master Data Analyst,"Job Description\nHello,\n\nMy name is Paul Jos...",4.4,ACT Consulting,"London, United Kingdom",1 to 50 employees,-1,Company - Private,Consulting,Business Services,Unknown / Non-Applicable,-1,0,48000,96000,48000.0,Parsippany,NJ
3553,SQL Developer/Data Analyst,"At Corbins Electric, we believe people are fir...",3.7,Corbins Electric,"Phoenix, AZ",501 to 1000 employees,1975,Company - Private,Construction,"Construction, Repair & Maintenance",$100 to $500 million (USD),"DP Electric, Helix Electric, Wilson Electric",0,94000,151000,94000.0,Phoenix,AZ
3030,"Senior Applied Data Scientist, Government","What we do\n\nAt Civis, we take a science-firs...",3.2,Civis Analytics,"Chicago, IL",51 to 200 employees,2013,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),-1,0,31000,56000,31000.0,Chicago,IL
3369,Data Engineer,Job Description\nWalker Elliott has partnered ...,-1.0,Walker Elliott,"Houston, TX",1 to 50 employees,-1,Company - Public,-1,-1,Unknown / Non-Applicable,-1,0,36000,71000,36000.0,Houston,TX
949,eDiscovery Data Analyst,Servient is looking for an eDiscovery Analyst ...,4.0,Servient,"Houston, TX",51 to 200 employees,2004,Company - Private,Enterprise Software & Network Solutions,Information Technology,$10 to $25 million (USD),-1,0,74000,123000,74000.0,Houston,TX
298,Data Analyst/Project Manager,The Data Analyst is a part of the Risk and Reg...,3.4,SMBC Group,"Tokyo, Japan",10000+ employees,1996,Company - Public,Investment Banking & Asset Management,Finance,$10+ billion (USD),"Bank Of Tokyo-Mitsubishi UFJ, Mizuho Financial...",0,27000,52000,27000.0,Jersey City,NJ

In [8]:
pd.set_option('max_rows',3000)

In [9]:
f['job_title'] = f['job_title'].str.lower()

In [10]:
f['job_title'].value_counts().to_frame()

                                                    job_title
data analyst                                              661
data scientist                                            276
data engineer                                             264
senior data analyst                                       139
senior data scientist                                      91
machine learning engineer                                  47
junior data analyst                                        45
big data engineer                                          43
business intelligence analyst                              40
business data analyst                                      39
senior data engineer                                       36
sr. data analyst                                           31
research scientist                                         24
lead data scientist                                        23
data analyst ii                                            23
sr. data scientist                                         23
data analyst junior                                        22
lead data analyst                                          22
data analyst iii                                           19
data analyst i                                             17
data modeler                                               17
data quality analyst                                       17
data governance analyst                                    16
sr data analyst                                            15
principal data scientist                                   15
financial data analyst                                     15
statistician (data scientist) *12 month roster*...         14
marketing data analyst                                     14
computer scientist                                         13
scientist                                                  13
federal - data scientist                                   13
sr. data engineer                                          13
data reporting analyst                                     13
clinical data analyst                                      11
data scientist - nationwide opportunities                  11
microsoft dynamics crm data analyst                        11
technical data analyst                                     11
quantum principal data scientist (industrial-pr...         10
quantum data scientist (industrial-process sector)         10
sr data scientist                                          10
research data analyst                                      10
quantitative researcher                                    10
quantum principal data scientist (industrial-di...         10
principal data scientist- public sector                     9
microsoft analytics consultant                              9
data science analyst                                        9
sql data analyst                                            9
data management analyst                                     8
federal - data engineer - senior                            8
data analyst iii (healthcare analytics)                     8
data warehouse analyst                                      8
product data analyst                                        8
quantitative analyst                                        8
data engineer ii                                            8
senior big data engineer                                    7
bioinformatics scientist                                    7
data analyst intern                                         7
analytics consultant                                        7
principal data engineer                                     7
healthcare data analyst                                     7
data analyst iv                                             6
data architect ii                                           6
data scientist ii                                           6
data security analyst                                       6
business/data analyst                                       6
pricing data analyst                                        6
epidemiology data analyst                                   6
cloud data engineer                                         6
operations data analyst                                     6
senior healthcare data analyst                              6
machine learning scientist                                  6
physical scientist                                          6
senior contract data analyst                                6
hr data analyst ii                                          6
scientist iii (molecular biology)                           6
data engineer iii                                           5
data analyst- remote                                        5
senior business intelligence analyst                        5
data scientist with security clearance                      5
data analyst, military forecasting                          5
data analyst â junior                                       5
senior machine learning engineer                            5
scientist i                                                 5
data science manager                                        5
master data analyst                                         5
general physical scientist                                  5
senior data scientist - nationwide opportunities            5
lead data engineer                                          5
data scientist (remote)                                     5
systems and data analyst                                    5
data architect                                              5
ny healthcare data/reporting analyst                        5
data analyst, data & analytics (advanced analyt...          5
data science architect                                      5
data engineer i                                             5
sr data engineer                                            5
data engineer (remote)                                      5
associate scientist                                         5
quantitative research analyst                               5
tx healthcare data/reporting analyst                        4
healthcare data/reporting analyst                           4
senior data quality analyst                                 4
data science resident - galvanize data science ...          4
data warehouse analyst iii                                  4
project scientist                                           4
provider analytics data analyst                             4
data analyst - veritystream                                 4
data analyst / developer                                    4
data analyst iii (population health , pharmacy,...          4
sr. enterprise bi data analyst                              4
business applications, infor analytics consultant           4
associate data scientist                                    4
applied scientist                                           4
federal - senior machine learning engineer                  4
reporting data analyst                                      4
sas data analyst                                            4
data scientist 2                                            4
data analyst, tax (affordable care act) (aca) (...          4
data analyst (supply chain) - may reside anywhe...          4
client data analyst                                         4
azure data engineer                                         4
senior claims data analyst                                  4
data science engineer                                       4
data analytics manager                                      4
big data/machine learning engineer - sr                     4
clinical laboratory scientist                               4
epidemiologist data analyst-urology                         4
big data analyst                                            4
data analyst manager                                        4
reporting and data analyst - (north american co...          4
sap data analyst                                            4
contract data analyst                                       4
aws data engineer                                           4
molecular researcher and data analyst                       4
quality data analyst                                        4
data science team lead                                      4
data base programmer/analyst                                4
survey data analyst                                         4
director of data science                                    4
system/data analyst                                         4
business analyst / data analyst                             3
data analyst 3 (san diego or atlanta, ga)                   3
analyst, financial master data                              3
lead data scientist, r&d team                               3
data & analytics consultant |                               3
data analyst, product                                       3
data visualization analyst                                  3
data systems analyst                                        3
sr. data governance analyst                                 3
fleet optimization data analyst (solar + storage)           3
data analyst assistant                                      3
business data analyst - i                                   3
data scientist iii                                          3
market data analyst                                         3
data management & analytics - consultant                    3
information security data analyst                           3
data science consultant                                     3
data & analytics consultant                                 3
data integration analyst                                    3
machine learning engineer (imaging)                         3
entry level / jr. data analyst                              3
director data scientist - data science hub                  3
environmental scientist                                     3
data engineer / data analyst                                3
technical business/data analyst                             3
staff software scientist, reproductive health               3
radar telemetry data analyst                                3
data science developer                                      3
hr data analyst                                             3
automotive data analyst                                     3
clinical scientist                                          3
data & reporting analyst                                    3
data and reporting analyst                                  3
systems analyst - data integration and etl process          3
data business analyst                                       3
staff big data engineer                                     3
operations research scientist                               3
senior product data analyst                                 3
environmental data analyst - disaster recovery              3
data engineer/analyst                                       3
data analyst-hedis & star                                   3
data analyst - intex developer                              3
analytics manager                                           3
data analyst - 20                                           3
senior data analyst - user growth                           3
data analyst/engineer                                       3
sr. big data engineer                                       3
data analyst, predictive analytics                          3
jr. data engineer                                           3
bi data analyst                                             3
division data and financial analyst                         3
associate scientist: microbiology                           3
data and user acceptance test analyst                       3
operation analytics manager                                 3
senior business data analyst                                3
business analytics manager                                  3
application vulnerability governance lead data ...          3
data engineer, machine learning                             3
business analyst/data analyst                               3
associate data engineer                                     3
finance data analyst                                        3
clinical laboratory scientist ii                            3
staff scientist                                             3
sr. data scientist ii                                       3
bi/data analyst                                             3
data integrity analyst                                      3
data scientist, analytics                                   3
data scientist / statistician                               3
data collection analyst                                     3
clinical safety scientist i                                 3
human factors scientist                                     3
network security system/data analyst                        2
sport & data analyst                                        2
data center migration pmo analyst/pmo lead                  2
senior research data analyst                                2
data analyst - mid-level                                    2
sr. business data analyst - enterprise risk                 2
lead data scientist - machine learning                      2
tactical data link (tdl) analyst                            2
senior scientist, bioassay services                         2
service operations data analyst                             2
data analyst, center on immigration and justice...          2
data analyst - intelliscript                                2
electronics engineering scientist                           2
health data analyst iv                                      2
senior data analyst, marketing                              2
analytical consultant                                       2
data scientist - analytics, trust & safety                  2
junior data analyst - sql programmer                        2
web analytics manager                                       2
senior data modeler                                         2
administrative assistant / data analyst support...          2
program data analyst                                        2
kafka data engineer (remote)                                2
software engineer - senior data analyst                     2
epic bi & analytics manager-remote                          2
full stack data engineer irving avp/c12                     2
7232 data engineer (analyst/programmer - career...          2
data analyst/project manager                                2
3rd shift environmental monitoring scientist                2
data engineer- customer data platform                       2
medical lab scientist (mls) evenings                        2
jpsc-5704 - data analyst                                    2
data analyst/scientist intern                               2
system test engineering scientist                           2
data engineer/tableau/alteryx                               2
vba software developer / it data analyst sql                2
senior research scientist                                   2
fall 2020 supply chain data analyst intern                  2
principal machine learning engineer                         2
medical lab scientist (mls) 2:00pm-10:30pm                  2
sap data analyst (contract)                                 2
data analyst-(analytics)                                    2
payment integrity data analyst                              2
data analyst - marketing                                    2
data scientist, analytics & inference                       2
pharmaceutical customer data analyst                        2
healthcare information and data analyst ii                  2
billingual chinese - data analyst                           2
data analyst-quality improvement services                   2
project regulatory/risk data analyst                        2
marketing data analyst coordinator                          2
data analyst - people analytics                             2
data analyst - rush infectious diseases                     2
data analyst & healthcare analytics                         2
cyber security research scientist 3 - sr. appli...          2
dps - fin - capps financial senior data analyst             2
senior analyst, data science                                2
data analyst v                                              2
behavorial health data analyst                              2
scientist, product development                              2
supply chain data analyst                                   2
data analyst/engineers                                      2
payment integrity data analyst job posting in #...          2
federal - data analyst                                      2
data analyst healthcare - experienced or entry ...          2
civil engineer/gis data analyst                             2
senior data analyst w/ collibra                             2
data analyst - sm                                           2
visiting undergraduate affairs data analyst - o...          2
senior data analyst, insights & analytics team ...          2
big data engineer/admin                                     2
vrl - clinical histocompatibility scientist tra...          2
data analyst - health, senior                               2
big data programmer analyst                                 2
diagnostic research scientist                               2
senior cloud data analyst                                   2
data analytics insights analyst                             2
data analyst, reporting                                     2
sr quantitative analyst                                     2
digital signal processing scientist                         2
business intelligence analyst senior - marketing            2
senior data analyst - data cataloging / data pr...          2
senior data architect                                       2
data scientist i                                            2
bi data analyst / specialist                                2
data engineer - business intelligence                       2
business analyst with data governance ,idq exp              2
sport and data scientist                                    2
data analyst (asset management / ediscovery)                2
software engineer - data analyst                            2
strategic data analyst iii - strategic planning...          2
data analyst / business lead generation special...          2
logistics data analyst                                      2
marketing data analyst, teleflora                           2
advertising data analyst                                    2
marketing data analyst - cpg                                2
simulation data analyst                                     2
data analyst 4                                              2
sr. scientist                                               2
data analyst (product analytics)                            2
sap master data analyst                                     2
data analyst (python), dallas, methods+mastery ...          2
data stewardship senior analyst                             2
data programmer/analyst                                     2
product development scientist - covid 19                    2
food scientist                                              2
data analyst - financial advisor services                   2
call center analytics manager                               2
master data management (mdm) - business systems...          2
data analyst, trust & safety                                2

In [11]:
f['job_title'] = f['job_title'].str.replace('sr','senior')

In [12]:
f['job_title'] = f['job_title'].str.replace('jr','junior')

In [13]:
f['job_title'] = f['job_title'].str.replace('.','')

In [14]:
# get rid of anything inside parentheses
# f['job_title'] = f['job_title'].str.replace('\(.+\)','')

Looks like we will have to parse out:

seniority: lead, principal, senior, head, director, manager 
job type: scientist, machine learning, engineering, analyst

In [15]:
f['scientist'] = f['job_title'].apply(lambda x: 1 if 'sci' in x else 0)

In [16]:
f['engineer'] = f['job_title'].apply(lambda x: 1 if 'engineer' in x else 0)

In [17]:
f['analyst'] = f['job_title'].apply(lambda x: 1 if 'analys' in x else 0)

In [18]:
f['machine'] = f['job_title'].apply(lambda x: 1 if 'machine' in x else 0)

In [19]:
f['business'] = f['job_title'].apply(lambda x: 1 if 'business' in x else 0)

In [20]:
f['manager'] = f['job_title'].apply(lambda x: 1 if 'manag' in x else 0)

In [21]:
f['senior'] = f['job_title'].apply(lambda x: 1 if 'senior' in x else 0)

In [22]:
f['junior'] = f['job_title'].apply(lambda x: 1 if 'junior' in x else 0)

In [23]:
f['big'] = f['job_title'].apply(lambda x: 1 if 'big' in x else 0)

In [24]:
f['lead'] = f['job_title'].apply(lambda x: 1 if 'lead' in x else 0)

In [25]:
f['principal'] = f['job_title'].apply(lambda x: 1 if 'principal' in x else 0)

In [26]:
f['director'] = f['job_title'].apply(lambda x: 1 if 'director' in x else 0)

In [27]:
f.columns

Index(['job_title', 'job_description', 'rating', 'company_name',
       'headquarters', 'size', 'founded', 'type_of_ownership', 'industry',
       'sector', 'revenue', 'competitors', 'easy_apply', 'low_salary',
       'high_salary', 'mid_salary', 'city', 'state', 'scientist', 'engineer',
       'analyst', 'machine', 'business', 'manager', 'senior', 'junior', 'big',
       'lead', 'principal', 'director'],
      dtype='object')

In [28]:
import pandas as pd

In [29]:
pd.set_option('max_columns',100)

In [30]:
f.head()

,job_title,job_description,rating,company_name,headquarters,size,founded,type_of_ownership,industry,sector,revenue,competitors,easy_apply,low_salary,high_salary,mid_salary,city,state,scientist,engineer,analyst,machine,business,manager,senior,junior,big,lead,principal,director
0,"data analyst, center on immigration and justic...",Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice,"New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,1,37000,66000,37000.0,New York,NY,0,0,1,0,0,0,0,0,0,0,0,0
1,quality data analyst,Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York,"New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,37000,66000,37000.0,New York,NY,0,0,1,0,0,0,0,0,0,0,0,0
2,"senior data analyst, insights & analytics team...",We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace,"New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,0,37000,66000,37000.0,New York,NY,0,0,1,0,0,0,1,0,0,0,0,0
3,data analyst,Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity,"McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,0,37000,66000,37000.0,New York,NY,0,0,1,0,0,0,0,0,0,0,0,0
4,reporting data analyst,ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel,"New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,1,37000,66000,37000.0,New York,NY,0,0,1,0,0,0,0,0,0,0,0,0

In [31]:
f.to_pickle('../data/interim/job_title_features.pkl')